name: Build Docs

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ['14']

    name: Build Docs
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      name: Set up Node
      with:
        node-version: ${{ matrix.node }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install Yarn
      run: npm install -g yarn

    - name: Install Dependencies
      run: yarn --scripts-prepend-node-path true

    - name: Build Documentation
      run: yarn docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
